### ISSUE TITLE
Set custom dialog title

### ISSUE THREAD

**Issue by saintjab** [holidaycheck/Permissify#1]
Hey mate, thanks for this amazing and simplified library. I have been struggling to change the default dialog title "Wee need permission.......". is it possible to change and how? Thanks

**Comment by domsu** [comment]
Hi @saintjab, yes this is possible. Here is an example:

```
PermissifyConfig permissifyConfig = new PermissifyConfig.Builder()
            .withDialogRationaleDialogFactory(new PermissifyConfig.AlertDialogFactory() {
                @Override
                public AlertDialog createDialog(Context context, String dialogMsg, DialogInterface.OnClickListener onClickListener) {
                    PermissifyConfig.AlertDialogFactory defaultDialogFactory = PermissionRationaleDialogFragment.getDefaultDialogFactory();
                    AlertDialog dialog = defaultDialogFactory.createDialog(context, dialogMsg, onClickListener);
                    dialog.setTitle("Your custom dialog title");

                    return dialog;
                }
            })
```

**Comment by saintjab** [comment]
Thanks for getting back to me. It working for me. However, I have another question: how do I request permissions in Fragment? I am getting 'Cannot resolve method getPermissifyManager()' on this 
`getPermissifyManager().callWithPermission(this, SMS_PERMISSION_REQUEST_ID, Manifest.permission.SEND_SMS,
                        new PermissionCallOptions.Builder()
                                .withDefaultDenyDialog(true)
                                .withDefaultRationaleDialog(false)
                                .build()
                );`
and same Cannot resolve method on the 
`super.onCallWithPermissionResult`  even though my Fragment implements PermissifyManager.Callback. 
Thanks

**Comment by domsu** [comment]
@saintjab To request permission in fragment you need to get permission manager from your activity.

```
PermissifyActivity permissifyActivity = (PermissifyActivity) getActivity();
PermissifyManager permissifyManager = permissifyActivity.getPermissifyManager();
permissifyManager.callWithPermission(...);
```

Call to `super.onCallWithPermissionResult` is not required.

I will add this to the documentation, thanks for reporting.
